language: java
sudo: false
install: true

jdk:
  - openjdk9

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar

script:
  - mvn clean install sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)

