language: java
sudo: false
install: true

jdk:
  - openjdk9

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar

addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token:
      secure: $SONAR_TOKEN

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY

after_success:
  - bash <(curl -s https://codecov.io/bash)

