language: java
sudo: false
install: true

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar

script:
  - mvn clean verify install cobertura:cobertura sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)

